---
env: development

exclude:
- "_assets/vendor"
- "_assets/styles/base"
- "_assets/styles/helpers"
- "_assets/styles/layouts"
- "_assets/styles/modules"
- "_assets/styles/states"
- "_assets/styles/vendor"
- "_assets/styles/app.scss"
- "_assets/js"

- "gulp"
- "bower.json"
- "Gemfile"
- "Gemfile.lock"
- "gulpfile.js"
- "gulp"
- "npm-debug.log"
- "package.json"
- "rev-manifest.json"
- "README.md"
- "node_modules"


include: [_assets]

source: ./_source
baseurl: /
url_prefix: http://localhost.corepath.dk
# development only
url_prefix_secure: http://localhost.corepath.dk

typekit_id: 'tvw4jri'

# Conversion
incremental: true
