---
env: development

exclude:
- "_assets/vendor"
- "_assets/styles/base"
- "_assets/styles/helpers"
- "_assets/styles/layouts"
- "_assets/styles/modules"
- "_assets/styles/states"
- "_assets/styles/vendor"
- "_assets/styles/app.scss"
- "_assets/js"

- "gulp"
- "bower.json"
- "Gemfile"
- "Gemfile.lock"
- "gulpfile.js"
- "gulp"
- "npm-debug.log"
- "package.json"
- "rev-manifest.json"
- "README.md"
- "node_modules"


include: [_assets]

permalink: pretty
source: ./_source
baseurl: /

typekit_id: 'tvw4jri'

# Conversion
incremental: true

# Collection options
timeline_types:
  fa-user-plus: New Member
  fa-dollar: Funding
  fa-building-o: Space
  fa-file-text-o: Legal
  fa-group: Pitch
  fa-newspaper-o: media
  fa-line-chart: Growth

# Collections
collections:
  news:
    output: true
  press-releases:
    output: true
  stories:
    output: true
  team:
    output: false
    _hide_content: true
  timeline:
    output: false
    _hide_content: true

defaults:
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "press-releases"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "stories"
    values:
      layout: "post"

# sass
sass:
    style: :compressed
