title: Avenue
source: ./_source
destination: ./_site
baseurl: /avenue/

assets:
  dirname: assets
  baseurl: /avenue/assets/
  sources:
    - _assets/js
    - _assets/stylesheets
    - _assets/images
  bundles:
    - 'application.css'
    - 'application.js'
  compress:
    #css: sass
    # js: uglifier
  cachebust: hard
  gzip:
  # - text/css
  # - application/javascript
