---
title: Cprobotics
timezone: UTC
collections:
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  press-releases:
    title: Press Releases
    output: true
  stories:
    title: Stories
    output: true
  team:
    title: Team
    output: false
  timeline:
    title: Timeline
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: news
  values:
    layout: post
    source: ''
    url: ''
    excerpt: ''
- scope:
    path: ''
    type: press-releases
  values:
    layout: post
    excerpt: ''
- scope:
    path: ''
    type: stories
  values:
    layout: post
    source: ''
    url: ''
    excerpt: ''
- scope:
    path: ''
    type: timeline
  values:
    timeline_type: 
    description: ''
- scope:
    path: ''
    type: team
  values:
    name: ''
    job_title: ''
    image: ''
    description: ''
    email: ''
    phone: ''
    staff_member: true
    board_member: false
    spokesperson: true
default_title: Flexible Industrial Automation | CP Robotics
default_description: Automation of industrial processes such as welding, milling and
  cutting by using Danish robotic technology.
env: development
exclude:
- _assets/vendor
- _assets/styles/base
- _assets/styles/helpers
- _assets/styles/layouts
- _assets/styles/modules
- _assets/styles/states
- _assets/styles/vendor
- _assets/styles/app.scss
- _assets/js
- gulp
- bower.json
- Gemfile
- Gemfile.lock
- gulpfile.js
- gulp
- npm-debug.log
- package.json
- rev-manifest.json
- README.md
- node_modules
include:
- _assets
permalink: pretty
baseurl: "/"
typekit_id: tvw4jri
incremental: true
timeline_types:
  fa-user-plus: New Member(s)
  fa-dollar: Funding
  fa-building-o: Space
  fa-file-text-o: Legal
  fa-group: Pitch
  fa-newspaper-o: Media
  fa-line-chart: Growth
  fa-plane: Travel
sass:
  style: :compressed
