clean:
  # These folders will be deleted
  - "_site"

browsersync:
  notify: true
  open:   external
  port:   3000
  url:    "localhost.corepath.dk"
  server:
    basedir: "_site/"
  xip:    false

jekyll:
  notification: "Running jekyll"
  notificationIncremental: "Running jekyll incremental"

javascript:
  dest: "_source/_assets/"
  siteDest: "_site/_assets/"
  # preload filename to output
  filenamePreload: "app-preload.js"
  # filename to output
  filename: "app.js"
  # notification message
  notification: "Running JavaScript"
  # Paths to JavaScript libraries, which are combined into one file
  srcPreload:
    - "_source/_assets/vendor/jquery/dist/jquery.js"

    # Core Foundation files, all Foundation components need this!
    - "_source/_assets/vendor/foundation-sites/js/foundation.core.js"

    # Individual Foundation components
    - "_source/_assets/vendor/foundation-sites/js/foundation.dropdownMenu.js"

  src:
    # Libraries requried by Foundation
    - "_source/_assets/vendor/what-input/what-input.js"

    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "_source/_assets/vendor/foundation-sites/js/foundation.abide.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.accordion.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.accordionMenu.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.drilldown.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.dropdown.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.equalizer.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.interchange.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.magellan.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.offcanvas.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.orbit.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.responsiveMenu.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.responsiveToggle.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.reveal.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.slider.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.sticky.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.tabs.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.toggler.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.tooltip.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.util.box.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.util.keyboard.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.util.mediaQuery.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.util.motion.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.util.nest.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.util.timerAndImageLoader.js"
    # - "_source/_assets/vendor/foundation-sites/js/foundation.util.touch.js"
    - "_source/_assets/vendor/foundation-sites/js/foundation.util.triggers.js"

    # Paths to other vendor plugins
    - "_source/_assets/js/vendor/jquery.email-protector.js"
    - "_source/_assets/js/vendor/jquery.royalslider.custom.min.js"
    - "_source/_assets/js/vendor/skrollr.js"
    - "_source/_assets/js/vendor/skrollr.stylesheets.js"

    # Paths to your own project code are here
    # All the files in this list are concatenated into app.js
    - "_source/_assets/js/**/*"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  dest: "_source/_assets/"
  siteDest: "_site/_assets/"
  notification: "Running Sass"
  src: "_source/_assets/styles/*.scss"

images:
  src: "_source/_assets/images/**/*"
  dest: "_source/_assets/images/"

watch:
  images: "_source/_assets/images/**/*"
  javascript: "_source/_assets/js/**/*"
  sass: "_source/_assets/styles/**/*"
  data: "_source/{_data,_posts}/**/*.{yml,xml}"
  pages:
    - "_source/**/*.{md,html,yml,xml}"
    - "_source/{_includes,_layouts,_pages,_posts}/**/*.{md,html,yml,xml}"
    - "!_site/**/*.*"
    - "!_source/_assets/**/*.*"

revision:
  revision:
    dest: "_site/_assets"
    manifest:
      dest: "./"
    src:
      - "_source/_assets/app.css"
      - "_source/_assets/app.js"
      - "_source/_assets/images/**"
  collect:
    dest: "_site"
    src:
      - "./rev-manifest.json"
      - "_site/*.{html,xml,txt,json,css,js}"
      - "_site/**/*.{html,xml,txt,json,css,js}"
      - "!_site/_assets/vendor"
